download:
  output_dir: /Users/edgarlqs/Downloads
  proxy: http://127.0.0.1:7897
  ytb_resolution: best
history:
  enabled: true
  storage_path: data/history.json
ui:
  theme: system
  window_height: 600
  window_width: 800
